# Elasticsearch Configuration for Steam Price Tracker
cluster.name: steam-price-tracker
node.name: node-1

# Network
network.host: 0.0.0.0
http.port: 9200

# Discovery
discovery.type: single-node

# Memory
bootstrap.memory_lock: true

# Security (für Development)
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true

# Indices
action.auto_create_index: true
